.travis.yml, CHANGELOG.md, README.md, appveyor.yml, dev_requirements.txt, octobot_commons/__init__.py, octobot_commons/event_tree.pxd, octobot_commons/event_tree.py, setup.py, tests/__init__.py, tests/test_event_tree.py
- Event tree composed by nodes with Event
=> New Feature: Event Tree

octobot_commons/event_tree.pxd, octobot_commons/event_tree.py, tests/test_event_tree.py
Requires https://github.com/Drakkar-Software/OctoBot-Commons/pull/5
=> [EventTree] Added get node without creation

octobot_commons/pretty_printer.py
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/110
=> update order format 

CHANGELOG.md, README.md, octobot_commons/__init__.py, requirements.txt
- Error message to exception logger
- Trade prettyprinter format
=> [Version] v1.3.0

CHANGELOG.md, README.md, octobot_commons/__init__.py, octobot_commons/constants.py
Depends on https://github.com/Drakkar-Software/OctoBot-Commons/pull/22
- Margin Portfolio key
=> [Version] v1.3.1

CHANGELOG.md, README.md, octobot_commons/__init__.py, octobot_commons/channels_name.py
Depends on https://github.com/Drakkar-Software/OctoBot-Trading/pull/131
=> [Channel] Add funding channel

CHANGELOG.md, README.md, octobot_commons/__init__.py, octobot_commons/timestamp_util.py
- Datetime to timestamp conversion
=> [Version] v1.3.3

CHANGELOG.md, README.md, octobot_commons/__init__.py, octobot_commons/channels_name.py
- Liquidations, Mini ticker and Book ticker Channels name
=> [Version] v1.3.4

CHANGELOG.md, README.md, octobot_commons/__init__.py, requirements.txt, setup.py
- [Requirement] cython to 0.29.16
- [Requirement] numpy to 0.18.2
- [Requirement] jsonschema to 3.2.0
- [Requirement] python-telegram-bot to 12.4.2
=> [Version] v1.3.5

CHANGELOG.md, README.md, octobot_commons/__init__.py, octobot_commons/tentacles_management/__init__.py
=> Fix imports 

CHANGELOG.md, README.md, octobot_commons/__init__.py
=> [Version] v1.3.9

octobot_commons/channels_name.py
Depends on https://github.com/Drakkar-Software/OctoBot-Commons/pull/42
=> [ChannelName] Add evaluators 

CHANGELOG.md, README.md, octobot_commons/__init__.py, requirements.txt
- Evaluators channel name
- [EventTree] node value time
- [EventTree] event clearing too early
- [EventTree] syntax
- AbtractEvaluator default description
=> [Version] v1.3.10  

CHANGELOG.md, README.md, octobot_commons/__init__.py, octobot_commons/data_util.pxd, octobot_commons/data_util.py, requirements.txt, tests/test_data_util.py
- [DataUtil] Improve shift implementation
Related to https://github.com/Drakkar-Software/OctoBot-Benchmarks/pull/2
=> [Version] v1.3.11

octobot_commons/evaluators_util.py, tests/test_evaluator_util.py
=> remove isnan check on eval note validation to allow for non numeric e… 

CHANGELOG.md, README.md, octobot_commons/__init__.py, requirements.txt, setup.py
=> [Version] v1.3.12

CHANGELOG.md, README.md, octobot_commons/__init__.py, octobot_commons/event_tree.pxd, octobot_commons/event_tree.py, tests/test_event_tree.py
- [EventTree] Events management
=> [EventTree] Remove event part 

CHANGELOG.md, README.md, octobot_commons/__init__.py, octobot_commons/logging/logging_util.pxd, octobot_commons/logging/logging_util.py
=> [Version] v1.3.17

CHANGELOG.md, README.md, octobot_commons/__init__.py, octobot_commons/logging/logging_util.pxd, octobot_commons/logging/logging_util.py
- Logging_util compiled errors
=> [Version] v1.3.18

CHANGELOG.md, README.md, octobot_commons/__init__.py, octobot_commons/pretty_printer.pxd, octobot_commons/pretty_printer.py
- [PrettyPrinter] Fix trade_pretty_printer cython header
=> [Version] v1.3.29

CHANGELOG.md, README.md, octobot_commons/__init__.py, octobot_commons/enums.py
- [Enums] ChannelConsumerPriorityLevels
=> [Version] v1.3.30

CHANGELOG.md, README.md, octobot_commons/__init__.py, requirements.txt, setup.py
- [Enums] ChannelConsumerPriorityLevels
=> [Version] v1.3.31

CHANGELOG.md, README.md, octobot_commons/__init__.py, requirements.txt
=> [Version] v1.3.34

CHANGELOG.md, README.md, octobot_commons/__init__.py, octobot_commons/asyncio_tools.py
- Asyncio tool wait_for_task_to_perform
=> [Version] v1.3.36

CHANGELOG.md, README.md, octobot_commons/__init__.py, requirements.txt, setup.py
=> [Version] v1.3.38

CHANGELOG.md, README.md, octobot_commons/__init__.py, requirements.txt, setup.py
=> [Version] v1.3.40

CHANGELOG.md, README.md, octobot_commons/__init__.py, octobot_commons/tentacles_management/class_inspector.pxd, octobot_commons/tentacles_management/class_inspector.py
to me merged after https://github.com/Drakkar-Software/OctoBot-Trading/pull/295
=> Simplify tentacles manager

CHANGELOG.md, README.md, octobot_commons/__init__.py, requirements.txt, setup.py
=> [Version] v1.3.43

octobot_commons/async_job.pxd, octobot_commons/async_job.py
=> log async job errors on successive failures for periodic updates

.coveragerc, octobot_commons/tentacles_management/class_inspector.py, tests/test_abstract_tentacle.py, tests/test_class_inspector.py, tests/test_dict_util.py, tests/test_singleton.py
- Add tests for class_inspector and Singleton
=> [ClassInspector] Fix missing subclass in get_all_classes_from_parent

CHANGELOG.md, README.md, octobot_commons/__init__.py, requirements.txt, setup.py
=> [Version] v1.4.1

CHANGELOG.md, README.md, octobot_commons/__init__.py, octobot_commons/async_job.py, octobot_commons/pretty_printer.py, requirements.txt, setup.py
=> [Version] v1.5.5

.github/workflows/main.yml, CHANGELOG.md, README.md, octobot_commons/__init__.py, octobot_commons/logging/logging_util.pxd, octobot_commons/logging/logging_util.py, requirements.txt
=> [Version] 1.5.17

CHANGELOG.md, README.md, octobot_commons/__init__.py, octobot_commons/configuration/configuration.py, octobot_commons/profiles/profile_sharing.py, tests/profiles/test_profile_sharing.py
Depends on https://github.com/Drakkar-Software/OctoBot-Commons/pull/181
=> [Version] v1.6.1

CHANGELOG.md, README.md, octobot_commons/__init__.py, octobot_commons/configuration/configuration.py, octobot_commons/logging/logging_util.py
uses https://github.com/Drakkar-Software/Errors-Server
=> Error publish

CHANGELOG.md, README.md, octobot_commons/__init__.py, octobot_commons/pretty_printer.py
Requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/656
=> [PrettyPrinter] Migrate to Asset

CHANGELOG.md, README.md, octobot_commons/__init__.py, octobot_commons/databases/database_caches/chronological_read_database_cache.py, octobot_commons/pretty_printer.py
requires https://github.com/Drakkar-Software/OctoBot-Trading/pull/700 (for enums)
=> [PrettyPrinter] adapt order and trade prettyprint and other

octobot_commons/display/display_translator.py, octobot_commons/enums.py, octobot_commons/pretty_printer.pxd, octobot_commons/pretty_printer.py
see pull request in octobot services here https://github.com/Drakkar-Software/OctoBot-Services/pull/136
=> [Portfolio] add current reference market value to portfolio_pretty_print

octobot_commons/pretty_printer.py
=> [PrettyPrinter] improve portfolio markdown display

CHANGELOG.md, README.md, octobot_commons/__init__.py, octobot_commons/async_job.py, octobot_commons/html_util.py, octobot_commons/logging/logging_util.py, tests/test_html_util.py
=> [HTML] add html summarizer

CHANGELOG.md, README.md, octobot_commons/__init__.py, octobot_commons/display/display_translator.py
can be remove once those are fixed:
- https://github.com/json-editor/json-editor/issues/1559
- https://github.com/json-editor/json-editor/issues/1621
=> Force disable dependencies == False due to JSON-editor schema issue
